version: '3.8'

services:
  app_test:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile.tests
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python -m pytest -s'
    env_file:
      - ./.env
  db:
    container_name: my_postgres
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${TEST_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
