version: '3.8'

services:
  app:
    container_name: my_app
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; uvicorn src.main:app --host 0.0.0.0 --port 8000'
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - ./.env
  db:
    container_name: my_postgres
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always