version: '3.8'

services:
  app:
    container_name: my_app
    build: ./Dockerfile.tests
    depends_on:
      - db
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python -m pytest -s'
    volumes:
      - ./src:/app/src
    restart: always
    env_file:
      - ./.env
  db:
    container_name: my_postgres
    image: postgres
    hostname: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    restart: always
    env_file:
      - ./.env
