"""empty message

Revision ID: 4a13a5872d8b
Revises: 
Create Date: 2024-04-17 14:55:23.249982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a13a5872d8b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('position_cur', sa.Integer(), nullable=False),
    sa.Column('position_prev', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('watches', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('repo')
    )
    op.create_table('repo_activities',
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo'], ['repos.repo'], ),
    sa.PrimaryKeyConstraint('repo', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_activities')
    op.drop_table('repos')
    # ### end Alembic commands ###
