"""empty message

Revision ID: bb280b005b4b
Revises: 
Create Date: 2024-04-24 09:00:16.497081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb280b005b4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repo', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('position_cur', sa.Integer(), nullable=False),
    sa.Column('position_prev', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('watchers', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('open_issues', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repo_activities',
    sa.Column('repo_id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('commits', sa.Integer(), nullable=False),
    sa.Column('authors', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('repo_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_activities')
    op.drop_table('repos')
    # ### end Alembic commands ###
